# Generated by Django 5.2.4 on 2025-07-07 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tag_name_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority_score',
            new_name='priority',
        ),
    ]
