# Generated by Django 5.2.4 on 2025-07-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_contextentry_insights_contextentry_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contextentry',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Context Entries'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Tasks'},
        ),
    ]
